package jp.afterfit.core.persistence.dao.generator;

import java.util.List;
import jp.afterfit.core.domain.entity.generator.Branch;
import jp.afterfit.core.domain.entity.generator.BranchCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    long countByExample(BranchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    int deleteByExample(BranchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    int insertSelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    List<Branch> selectByExampleWithRowbounds(BranchCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    List<Branch> selectByExample(BranchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    Branch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Branch record, @Param("example") BranchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Branch record, @Param("example") BranchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.branch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Branch record);
}