package jp.afterfit.core.persistence.dao.generator;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import jp.afterfit.core.domain.entity.generator.Changelog;
import jp.afterfit.core.domain.entity.generator.ChangelogCriteria;

@Mapper
public interface ChangelogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    long countByExample(ChangelogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    int deleteByExample(ChangelogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    int insert(Changelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    int insertSelective(Changelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    List<Changelog> selectByExampleWithRowbounds(ChangelogCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    List<Changelog> selectByExample(ChangelogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    Changelog selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Changelog record, @Param("example") ChangelogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Changelog record, @Param("example") ChangelogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Changelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changelog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Changelog record);
}