package jp.afterfit.core.persistence.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import jp.afterfit.core.domain.entity.generator.OauthAccessToken;
import jp.afterfit.core.domain.entity.generator.OauthAccessTokenCriteria;
import jp.afterfit.core.domain.entity.generator.OauthAccessTokenWithBLOBs;

@Mapper
public interface OauthAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    long countByExample(OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int deleteByExample(OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int insert(OauthAccessTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int insertSelective(OauthAccessTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    List<OauthAccessTokenWithBLOBs> selectByExampleWithBLOBsWithRowbounds(OauthAccessTokenCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    List<OauthAccessTokenWithBLOBs> selectByExampleWithBLOBs(OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    List<OauthAccessToken> selectByExampleWithRowbounds(OauthAccessTokenCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    List<OauthAccessToken> selectByExample(OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    OauthAccessTokenWithBLOBs selectByPrimaryKey(String authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OauthAccessTokenWithBLOBs record, @Param("example") OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") OauthAccessTokenWithBLOBs record, @Param("example") OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OauthAccessToken record, @Param("example") OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OauthAccessTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OauthAccessTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OauthAccessToken record);
}