package jp.afterfit.core.persistence.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import jp.afterfit.core.domain.entity.generator.OauthClientToken;
import jp.afterfit.core.domain.entity.generator.OauthClientTokenCriteria;

@Mapper
public interface OauthClientTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    long countByExample(OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int deleteByExample(OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int insert(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int insertSelective(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    List<OauthClientToken> selectByExampleWithBLOBsWithRowbounds(OauthClientTokenCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    List<OauthClientToken> selectByExampleWithBLOBs(OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    List<OauthClientToken> selectByExampleWithRowbounds(OauthClientTokenCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    List<OauthClientToken> selectByExample(OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    OauthClientToken selectByPrimaryKey(String authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_client_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OauthClientToken record);
}