package jp.afterfit.core.persistence.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import jp.afterfit.core.domain.entity.generator.OauthApprovals;
import jp.afterfit.core.domain.entity.generator.OauthApprovalsCriteria;

@Mapper
public interface OauthApprovalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    long countByExample(OauthApprovalsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    int deleteByExample(OauthApprovalsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    int insert(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    int insertSelective(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    List<OauthApprovals> selectByExampleWithRowbounds(OauthApprovalsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    List<OauthApprovals> selectByExample(OauthApprovalsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OauthApprovals record, @Param("example") OauthApprovalsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OauthApprovals record, @Param("example") OauthApprovalsCriteria example);
}