package jp.afterfit.core.persistence.dao.generator;

import java.util.List;
import jp.afterfit.core.domain.entity.generator.PaymentOrder;
import jp.afterfit.core.domain.entity.generator.PaymentOrderCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PaymentOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    long countByExample(PaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    int deleteByExample(PaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    int insert(PaymentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    int insertSelective(PaymentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    List<PaymentOrder> selectByExampleWithRowbounds(PaymentOrderCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    List<PaymentOrder> selectByExample(PaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    PaymentOrder selectByPrimaryKey(Integer requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaymentOrder record, @Param("example") PaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaymentOrder record, @Param("example") PaymentOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentOrder record);
}