package jp.afterfit.core.persistence.dao.generator;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import jp.afterfit.core.domain.entity.generator.RequestComment;
import jp.afterfit.core.domain.entity.generator.RequestCommentCriteria;

@Mapper
public interface RequestCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    long countByExample(RequestCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    int deleteByExample(RequestCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    int insert(RequestComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    int insertSelective(RequestComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    List<RequestComment> selectByExampleWithRowbounds(RequestCommentCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    List<RequestComment> selectByExample(RequestCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    RequestComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RequestComment record, @Param("example") RequestCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RequestComment record, @Param("example") RequestCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RequestComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.request_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RequestComment record);
}