package jp.afterfit.core.domain.entity.generator;

import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class OauthApprovals implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_approvals.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_approvals.clientid
     *
     * @mbg.generated
     */
    private String clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_approvals.scope
     *
     * @mbg.generated
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_approvals.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_approvals.expiresat
     *
     * @mbg.generated
     */
    private Date expiresat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_approvals.lastmodifiedat
     *
     * @mbg.generated
     */
    private Date lastmodifiedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.oauth_approvals
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}