package jp.afterfit.core.domain.entity.generator;

import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class RequestHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.request_id
     *
     * @mbg.generated
     */
    private Integer requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.step
     *
     * @mbg.generated
     */
    private Short step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.assigned_user
     *
     * @mbg.generated
     */
    private String assignedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.priority
     *
     * @mbg.generated
     */
    private String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.deadline
     *
     * @mbg.generated
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.detail_request
     *
     * @mbg.generated
     */
    private String detailRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.request_status
     *
     * @mbg.generated
     */
    private String requestStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request_history.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.request_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}