package jp.afterfit.core.domain.entity.generator;

import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Request implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.request_type_id
     *
     * @mbg.generated
     */
    private String requestTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.priority
     *
     * @mbg.generated
     */
    private String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.deadline
     *
     * @mbg.generated
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.request_status
     *
     * @mbg.generated
     */
    private String requestStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.assigned_user
     *
     * @mbg.generated
     */
    private String assignedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.step
     *
     * @mbg.generated
     */
    private Short step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.request.user_approved_prev
     *
     * @mbg.generated
     */
    private String userApprovedPrev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.request
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}